[auth.email.template.invite]
subject = "You’re invited to BuxTax"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm your BuxTax signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your BuxTax password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your BuxTax magic link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm your new email for BuxTax"
content_path = "./supabase/templates/email_change.html"

[auth.email.template.reauthentication]
subject = "Your BuxTax verification code"
content_path = "./supabase/templates/reauthentication.html"


